# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

before_install:
  - sudo apt-get install libproj-dev libgeos++-dev
  - export CURWD=`pwd`
  - cd
  - wget http://download.osgeo.org/gdal/2.1.0/gdal-2.1.0.tar.gz
  - tar zxf gdal-2.1.0.tar.gz
  - cd gdal-2.1.0
  - ./configure
  - make
  - sudo make install
  - cd
  - wget http://download.osgeo.org/proj/proj-4.9.2.tar.gz
  - tar zxvf proj-4.9.2.tar.gz
  - cd proj-4.9.2
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - cd $CURWD


language: R
sudo: required
r_github_packages:
  - tidyverse/ggplot2
  - dkahle/ggmap

warnings_are_errors: false
cache: packages
after_success:
  - Rscript -e 'covr::codecov()'
